import os
from PyStemmusScope import StemmusScope
from PyStemmusScope import save

# user must provide the correct path
path_to_config_file = "./config_file_snellius_sensitivity_analysis.txt"
path_to_exe_file = "./exe/STEMMUS_SCOPE_SS.exe"

# create an an instance of the model
model = StemmusScope(config_file=path_to_config_file, model_src_path=path_to_exe_file)

# setup the model
# here you can change the location and start & end time
config_path = model.setup(
    Location="CH-HTC",
    StartTime="2022-01-01T00:00",
    EndTime="2022-01-02T01:30",
)
# Set LD_LIBRARY_PATH
# matlab_path = !whereis MATLAB
# matlab_path = matlab_path.s.split(": ")[1]
# os.environ['LD_LIBRARY_PATH'] = (
#     f"{matlab_path}/MATLAB_Runtime/v910/runtime/glnxa64:"
#     f"{matlab_path}/MATLAB_Runtime/v910/bin/glnxa64:"
#     f"{matlab_path}/MATLAB_Runtime/v910/sys/os/glnxa64:"
#     f"{matlab_path}/MATLAB_Runtime/v910/extern/bin/glnxa64:"
#     f"{matlab_path}/MATLAB_Runtime/v910/sys/opengl/lib/glnxa64")
# print(os.environ['LD_LIBRARY_PATH'])
# new config file genertaed to run the model
print(f"New config file {config_path}")

# see input and output paths generated by the model
print(f'Model input dir {model.config["InputPath"]}')
print(f'Model output dir {model.config["OutputPath"]}')
print(model)

# run the model
result = model.run()
result

# save output in netcdf format
# required_netcdf_variables = "~/STEMMUS_SCOPE/utils/csv_to_nc/required_netcdf_variables.csv"
# nc_file_name = save.to_netcdf(config_path, required_netcdf_variables)
# print(nc_file_name)