import os
from PyStemmusScope import StemmusScope
from PyStemmusScope import save
import subprocess

path_to_config_file ='/media/geo/Crystal/P1/sensitivitiy_analysis_CLM5_scheme/STEMMUS_SCOPE_SS/run_model_on_snellius/config_file_snellius_sensitivity_analysis.txt'
path_to_exe_file  = '/media/geo/Crystal/P1/sensitivitiy_analysis_CLM5_scheme/STEMMUS_SCOPE_SS/run_model_on_snellius/exe/STEMMUS_SCOPE_SS'
# subprocess.run(exe_file, config_file)

# # # user must provide the correct path
# path_to_config_file = "./config_file_snellius_sensitivity_analysis.txt"
# path_to_exe_file = "./exe/STEMMUS_SCOPE_SS"


# Set LD_LIBRARY_PATH
bash_command = 'whereis MATLAB'
matlab_path = os.popen(bash_command).read()
matlab_path = matlab_path.split(": ")[1]
matlab_path = matlab_path.split("\n")[0]
# matlab_path = os.system('whereis MATLAB')

# matlab_path = matlab_path.s.split(": ")[1]
os.environ['LD_LIBRARY_PATH'] = (
    f"{matlab_path}/MATLAB_Runtime/v910/runtime/glnxa64:"
    f"{matlab_path}/MATLAB_Runtime/v910/bin/glnxa64:"
    f"{matlab_path}/MATLAB_Runtime/v910/sys/os/glnxa64:"
    f"{matlab_path}/MATLAB_Runtime/v910/extern/bin/glnxa64:"
    f"{matlab_path}/MATLAB_Runtime/v910/sys/opengl/lib/glnxa64")
print(os.environ['LD_LIBRARY_PATH'])



# create an instance of the model
model = StemmusScope(config_file=path_to_config_file, model_src_path=path_to_exe_file)

# setup the model
# here you can change the location and start & end time
config_path = model.setup(
    Location="CH-HTC",
    StartTime="2022-01-01T00:00",
    EndTime="2022-01-02T01:30",
)

# new config file genertaed to run the model
print(f"New config file {config_path}")

# see input and output paths generated by the model
print(f'Model input dir {model.config["InputPath"]}')
print(f'Model output dir {model.config["OutputPath"]}')
print(f'Model exe file{model.exe_file}')
print(f'Model cfg file{model.cfg_file}')

# subprocess.run(model.exe_file, model.cfg_file)
# run the model
result = model.run()
result

# save output in netcdf format
# required_netcdf_variables = "/media/geo/Crystal/P1/sensitivitiy_analysis_CLM5_scheme/STEMMUS_SCOPE/utils/csv_to_nc/required_netcdf_variables.csv"
# nc_file_name = save.to_netcdf(config_path, required_netcdf_variables)
# print(nc_file_name)